# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ec084f703f9fc2d8bd07864b66c9530de8d0570891fe32902fe5a1961203ad66975ede5b1508aac70548f50679359013f5810e099228162c5f1666dd38f633

test:
  secret_key_base: c47915089a97eca46bd9c3c8d8e74ee6ef3c8d194277e59bc6e096c0667e1cafdac42779c405d57f32c9a5c8b0f1d5810f1141af87d222edf4dc9deba35255b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
